#Miner
enable_miner: True
target_miner_tag: "latest-arm64"
seed_node: "/ip4/199.229.250.69/tcp/2154"
seed_peer: "/p2p/11hVUgp5hMrZhCKcbamRUL1RnDxbEdpDVytSZsiGSkjRJxbujwa"
#Packet Forwarder
enable_packet_forwarder: True
target_pf_image: "ghcr.io/heliumdiy/sx1302_hal" # heliumdiy/sx1302_hal on docker hub
target_pf_tag: "0.0.3"
# Helium Workarounds
workarounds_log_only_failed: True
#Loki & Prometheus
enable_node_exporter: False
enable_grafana_agent: True
enable_json_exporter: False
target_loki_server: "http://1.2.3.4:3100/loki/api/v1/push" # Needed by the Grafana Agent to Ship Logs to Loki
prometheus_remote_write_endpoint: "" # Needed by the Grafana Agent to Ship Metrics to Prometheus
prometheus_remote_write_username: "" # Needed by the Grafana Agent to Ship Metrics to Prometheus
prometheus_remote_write_password: "" # Needed by the Grafana Agent to Ship Metrics to Prometheus
enable_cadvisor: True
enable_docker_daemon_metrics: True
docker_daemon_metrics_port: 9323
# Workarounds
enable_workarounds: True
# Raspberry Pi Configuration
enable_gui: False
enable_autologin: False
enable_bootwait: False
enable_bootsplash: False
enable_camera: False
enable_vnc: False
enable_spi: True
enable_i2c: True
enable_serial: False
enable_serial_hw: True
enable_onewire: False
enable_rgpio: False
#Docker
docker_convenience_install: True
docker_version: "latest"
docker_install_recommends: true
docker_install_compose: true
docker_users: [pi]
docker_pip_executable: pip3
# VPN Configuration
enable_tailscale: True
enable_openvpn: True # Also need to define openvpn_config
# Tailscale Args
tailscale_args: "--accept-routes=true  --advertise-routes={{ tailscale_subnet_cidr}}"
tailscale_auth_key: !vault | # Fake example encrypted by Ansible Vault
          $ANSIBLE_VAULT;1.2;AES256;tailscale
          32616238303134343065613038383933333733383765653166346564363332343761653761646363
          6637666565626333333664363739613366363461313063640a613330393062323161636235383936
          37373734653036613133613533376139383138613164323661386362376335316364653037353631
          6539646561373535610a643334396234396332376431326565383432626232383131303131363362
          3537
# Aliases
enable_miner_aliases: True