---
version: "2.1"
services:
{% if enable_packet_forwarder %}

  packet_forwarder:
    image: {{ target_pf_image }}:{{ target_pf_tag }}
    container_name: pf
    environment:
      - VENDOR={{ target_hotspot_vendor }}
      - REGION={{ target_miner_region }}
      - CONCENTRATOR_INTERFACE={{ target_pf_concentrator_interface }}
      - CONCENTRATOR_MODEL={{ target_pf_concentrator_model }}
{% if packet_forwarder_config_file_path %}
      - CONFIG_FILE=/opt/packet_forwarder/configs/local_conf.json
{% endif %}
    volumes:
      - /home/pi/pf:/opt/packet_forwarder/configs
      - /sys/class/gpio:/sys/class/gpio
    devices:
      - /dev/spidev0.0:/dev/spidev0.0
      - /dev/spidev0.1:/dev/spidev0.1
    cap_add:
      - SYS_RAWIO
    networks:
      - helium
    privileged: true
    restart: unless-stopped  
    logging:
      driver: json-file  
      options:
        tag: "{{ '{{' }}.ImageName{{ '}}' }}|{{ '{{' }}.Name{{ '}}' }}|{{ '{{' }}.ImageFullID{{ '}}' }}|{{ '{{' }}.FullID{{ '}}' }}"
{% endif %}
{% if enable_miner %}

  miner:
    image: quay.io/team-helium/miner:{{ target_miner_tag }}
    container_name: miner
    environment:
      - REGION_OVERRIDE={{ target_miner_region }}
    ports:
      - "44158:44158/tcp"
      - "1680:1680/udp"
      - "4467:4467/tcp"
    volumes:
      - /home/pi/miner_data:/var/data
      - /home/pi/miner_config/sys.config:/config/sys.config
    cap_add:
      - SYS_RAWIO
    devices:
{% if target_hotspot_vendor == "pisces" %}
      - /dev/i2c-0:/dev/i2c-1
{% else %}
      - /dev/i2c-1:/dev/i2c-1
{% endif %}
    networks:
      - helium
    ulimits:
      nofile:
        soft: 64000
        hard: 64000
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        tag: "{{ '{{' }}.ImageName{{ '}}' }}|{{ '{{' }}.Name{{ '}}' }}|{{ '{{' }}.ImageFullID{{ '}}' }}|{{ '{{' }}.FullID{{ '}}' }}"
{% endif %}
{% if enable_grafana_agent %}

  grafana-agent:
    image: grafana/agent:latest
    container_name: grafana-agent
    volumes:
      - /data/var/lib/docker/containers:/containers #Promtail Docker Logs
      - /var/log/journal:/journal #Journal logs
      - /home/pi/grafana-agent/agent.yml:/etc/agent/agent.yml # Agent Config
      - /:/host/root:ro,rslave # rootfs / node_exporter
      - /sys:/host/sys:ro,rslave # sys / node_exporter
      - /proc:/host/proc:ro,rslave #processes / node_exporter
    command: -config.file=/etc/agent/agent.yml -config.expand-env=true
    networks:
      - helium
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        tag: "{{ '{{' }}.ImageName{{ '}}' }}|{{ '{{' }}.Name{{ '}}' }}|{{ '{{' }}.ImageFullID{{ '}}' }}|{{ '{{' }}.FullID{{ '}}' }}"
{% endif %}
{% if enable_cadvisor %}

  cadvisor:
    image: unibaktr/cadvisor:0.39.0
    container_name: cadvisor
    volumes:
        - /:/rootfs:ro
        - /var/run:/var/run:ro
        - /sys:/sys:ro
        - /var/lib/docker/:/var/lib/docker:ro
        - /dev/disk/:/dev/disk:ro
        - /etc/machine-id/:/etc/machine-id:ro
    devices:
        - /dev/kmsg:/dev/kmsg:ro
    ports:
        - "8080:8080"
    networks:
      - helium
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        tag: "{{ '{{' }}.ImageName{{ '}}' }}|{{ '{{' }}.Name{{ '}}' }}|{{ '{{' }}.ImageFullID{{ '}}' }}|{{ '{{' }}.FullID{{ '}}' }}"
{% endif %}
{% if enable_json_exporter %}

  json-exporter:
    image: quay.io/prometheuscommunity/json-exporter@sha256:{{ target_json_exporter_sha256 }}
    container_name: json-exporter
    volumes:
      - /home/pi/json-exporter:/etc/json-exporter
    command: --config.file=/etc/json-exporter/config.yml
    networks:
      - helium
    restart: unless-stopped
    ports:
      - "7979:7979"
    logging:
      driver: json-file
      options:
        tag: "{{ '{{' }}.ImageName{{ '}}' }}|{{ '{{' }}.Name{{ '}}' }}|{{ '{{' }}.ImageFullID{{ '}}' }}|{{ '{{' }}.FullID{{ '}}' }}"

{% endif %}
{% if enable_workarounds %}

  helium_workarounds:
    image: ghcr.io/heliumdiy/helium_workarounds:latest
    container_name: helium_workarounds
    volumes:
      - /home/pi/miner_data/log:/log
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - LOG_ONLY_FAILED={{ workarounds_log_only_failed }}
    networks:
      - helium
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        tag: "{{ '{{' }}.ImageName{{ '}}' }}|{{ '{{' }}.Name{{ '}}' }}|{{ '{{' }}.ImageFullID{{ '}}' }}|{{ '{{' }}.FullID{{ '}}' }}"
{% endif %}

networks:
  helium:
   driver: bridge
   ipam:
    config:
     - subnet: 172.16.57.0/24
